import subprocess
import random
import os
import pandas as pd

def run_solver(L_max, A, N, output_file):
    """
    Run the Fortran solver to generate raw data to train your model and save it to the specified output file.

    Args:
        L_max (float): Maximum length of the box.
        A (float): range of the coefficients of the potential polynomial [-A, +A].
        N (int): number of times to run the Fortran solver. Each run generates one data point.
        output_file (str): Path to the output file where the solver will save the raw data.
    """
    if os.path.exists('training_data.csv'):
        os.remove('training_data.csv')
        open('training_data.csv', 'w').close()
    else:
        open('training_data.csv', 'w').close()

    for i in range(N):
        L = random.uniform(0, L_max)
    
        coeffs = [random.uniform(-A, A) for _ in range(5)]
    
        with open('coefficients.txt', 'w') as f:
            f.write(f"{L}\n")
            for coeff in coeffs:
                f.write(f"{coeff}\n")
    
        subprocess.run(['./solve_poly'])

        print(f"Done. Generated {N} training samples!")

    
def convert_solved_data(file_path, new_file_path):
    """
    Load the raw data from the Fortran solver output file and transform the coefficients into a dimensionless format.
    
    Args:
        file_path (str): Path to the output file generated by the Fortran solver.
        new_file_path (str): Path to the output file where the transformed data will be saved.
    """
    df = pd.read_csv(file_path)

    if os.path.exists(new_file_path):
        os.remove(new_file_path)
        open(new_file_path, 'w').close()
    else:
        open(new_file_path, 'w').close()

        df.columns = ["Box Length", "Coefficient 0", "Coefficient 1", "Coefficient 2", "Coefficient 3", "Coefficient 4", "Energy 0", "Energy 1", "Energy 2", "Energy 3", "Energy 4", "Energy 5", "Energy 6", "Energy 7", "Energy 8", "Energy 9"]

    for i in range(5):
        df[f'Coefficient {i}'] = df[f'Coefficient {i}'] * df['Box Length']**(i+2)

    df.to_csv(new_file_path, index=False)

    print("Coefficients transformed to dimensionless format")
    return df