"""
ANN-1D-PIB: Data Generator

Module for generating training data for 1D particle in a box models using the Fortran solver.
"""
import subprocess
import numpy as np
from scipy.stats import qmc
import os
import pandas as pd
from pathlib import Path

def run_solver(L_max, A, N, output_file):
    """
    Generate training data by running the Fortran solver multiple times with random parameters.

    Args:
        L_max (float): Maximum box length.
        A (float): Maximum absolute value for polynomial coefficients.
        N (int): Number of training samples to generate.
        output_file (str): Path to the output file where the generated data will be saved.
    """
    root = Path(__file__).resolve().parent.parent
    dataset_dir = root / "dataset"
    exe_path = dataset_dir / "solve_poly.exe"

    output_path = dataset_dir / Path(output_file).name
    if os.path.exists(output_path):
        os.remove(output_path)
    open(output_path, 'w').close()

    L_min = 0.1  

    t = np.linspace(0.0, 1.0, N, endpoint = True)

    a0 = -A + 2 * A * t
    a1 = -A + 2 * A * t
    a2 = -A + 2 * A * t
    a3 = -A + 2 * A * t
    a4 = -A + 2 * A * t
    L_vals = L_min + (L_max - L_min) * t

    for i in range(N):
        L = L_vals[i]
        coeffs = [a0[i], a1[i], a2[i], a3[i], a4[i]]

        with open(dataset_dir / 'coefficients.txt', 'w') as f:
            f.write(f"{L}\n")
            for coeff in coeffs:
                f.write(f"{coeff}\n")

        subprocess.run([str(exe_path)], cwd = str(dataset_dir), check = True)

    print(f"Done. Generated {N} training samples!")

def convert_headers(file_path, new_file_path):
    """
    Load the raw data from the Fortran solver output file and add appropriate headers.
    
    Args:
        file_path (str): Path to the output file generated by the Fortran solver.
        new_file_path (str): Path to the output file where the headers will be added.
    """
    df = pd.read_csv(file_path, header=None)

    df.columns = [
        "Box Length",
        "Coefficient 0", "Coefficient 1", "Coefficient 2", "Coefficient 3", "Coefficient 4",
        "Energy 0", "Energy 1", "Energy 2", "Energy 3", "Energy 4",
        "Energy 5", "Energy 6", "Energy 7", "Energy 8", "Energy 9",
    ] 

    if os.path.exists(new_file_path):
        os.remove(new_file_path)
    open(new_file_path, 'w').close()

    df.to_csv(new_file_path, index=False)
    return df

def convert_solved_data(file_path, new_file_path):
    """
    Load the raw data from the Fortran solver output file and transform the coefficients into a dimensionless format.
    
    Args:
        file_path (str): Path to the output file generated by the Fortran solver.
        new_file_path (str): Path to the output file where the transformed data will be saved.
    """
    df = pd.read_csv(file_path, header=None)

    df.columns = [
        "Box Length",
        "Coefficient 0", "Coefficient 1", "Coefficient 2", "Coefficient 3", "Coefficient 4",
        "Energy 0", "Energy 1", "Energy 2", "Energy 3", "Energy 4",
        "Energy 5", "Energy 6", "Energy 7", "Energy 8", "Energy 9",
    ] 

    if os.path.exists(new_file_path):
        os.remove(new_file_path)
    open(new_file_path, 'w').close()
    
    for i in range(5):
        df[f'Coefficient {i}'] = df[f'Coefficient {i}'] * df['Box Length']**(i+2)

    df.to_csv(new_file_path, index=False)

    print("Coefficients transformed to dimensionless format")
    return df